# material is the bukkit name for the material.
# requirements is the amount of the material needed to create a reinforcement.
# return is the amount of material to return.
# percent_chance is the chance to return the block. Scales with damage.
# scale_amount is, if maturation is enabled, the amount extra to damage a block if it is not fully matured.  The forumla for calculating the extra damage is 1/(1-((time left of maturation) / (default amount of time for maturation))) * scale.  So if a block has 5 minutes left of maturation on a 10 minute default period with a scale of 3 we do 1/(5 / 10) * 3 = 6 damage. Setting scale amount to 0 disables this function.
# effect allows to add particles around a reinforced block when it is created or damaged.
#  type: The bukkit name of the particle.
#  id: the item/block/data id for the effect
#  data: the data value of the block/item for the effect
#  offsetX: the amount to be randomly offset by in the X axis
#  offsetY: the amount to be randomly offset by in the Y axis
#  offsetZ: the amount to be randomly offset by in the Z axis
#  speed: the speed of the particles
#  particleCount: the amount of particle to display. 
#  view_distance: the distance from which players will be able to see the effect. default is 16. 
internal_logging: true
command_logging: true
break_logging: true
reinf_logging: false
reinforcements:
 diamond:
  material: DIAMOND
  requirements: 1
  return: 1
  percent_chance: 100
  hit_points: 1800
# mature time is in minutes
  mature_time: 1440
  acid_time: 1440
  scale_amount: 1
  lore:
  effect:
   type: FLYING_GLYPH
   speed: 0.5
   particleCount: 50
# Delete the comment char to use lore.  Three spaces are required 
# after lore. You can add multiple lines by adding -
#   - Some string representation required for this reinforcement.
#
# # Uncomment below to add limits to what blocks this reinforcement can be applied to
# reinforceables:
#   - STONE
 iron:
  material: IRON_INGOT
  requirements: 1
  return: 1
  percent_chance: 100
  hit_points: 250
  mature_time: 60
  acid_time: 60
  scale_amount: 1
  lore:
  effect:
   type: FLYING_GLYPH
   speed: 0.5
   particleCount: 50
 stone:
  material: STONE
  requirements: 1
  return: 1
  percent_chance: 100
  hit_points: 25
  mature_time: 10
  acid_time: 10
  scale_amount: 1
  lore:
  effect:
   type: FLYING_GLYPH
   speed: 0.5
   particleCount: 50
 bedrock:
  material: BEDROCK
  requirements: 1
  return: 0
  percent_chance: 100
  hit_points: 147483646
  mature_time: 147483646
  acid_time: 147483646
  scale_amount: 1
  lore:
  effect:
   type: FLYING_GLYPH
   speed: 0.5
   particleCount: 50
#natural_reinforcements:
 #diamond_ore:
  #material: DIAMOND_ORE
  #hit_points: 60
non_reinforceables:
 - BEDROCK
 - ENDER_PORTAL_FRAME
 - SAPLING
 - LONG_GRASS
 - DEAD_BUSH
 - PISTON_EXTENSION
 - PISTON_MOVING_PIECE
 - RED_ROSE
 - YELLOW_FLOWER
 - BROWN_MUSHROOM
 - RED_MUSHROOM
 - TNT
 - CROPS
 - FIRE
 - SNOW
 - ICE
 - CACTUS
 - SUGAR_CANE_BLOCK
 - PORTAL
 - CAKE_BLOCK
 - PUMPKIN_STEM
 - MELON_STEM
 - VINE
 - NETHER_WARTS
 - ENDER_PORTAL
reset_player_state: 300
enable_maturation: true
# The max amount of reinforcements to keep loaded
max_cache_size: 20000
# The amount of minutes to keep a reinforcement loaded
max_cache_load_time: 10
redstone_distance: 7
acidblock_material: GOLD_BLOCK
# If set to true then instead of dropping the reinforcement a block with the specified reinforcement value will be dropped.
drop_reinforced_block: false
save_interval_ticks: 500
# reinforcement_damageMultiplier is m where BlockDamage = 2 ^ (n/m) where n is equal to the number of days the group has been inactive
reinforcement_damageMultiplier: 7
mysql:
 hostname: "localhost"
 port: 3306
 dbname: "bukkit"
 username: "bukkit"
 password: ""
# Shows reinforcement information as percentile value
show_health_as_percent: false
# Whether players are automatically put in reinforcement bypass mode on login
default_bypass_mode: false
